#! /usr/bin/env node
// -*- js -*-
process.stdin.setEncoding('utf8');
const fs = require("fs");
const copy = require("../tools/copydir.js");
const WebpackDevServer = require("webpack-dev-server");
var webpack = require("webpack");
function readline() {
  return new Promise((resolve, reject) => {
    process.stdin.resume();
    process.stdin.on('data', function (data) {
      process.stdin.pause(); // stops after one line reads
      resolve(data.replace(/\r\n/g, "").replace("\n", ""));
    });
  });
}
const runner = {
  async pull() {
    await this.dopull();
    console.log("success");
  },
  async dopull() {
    return new Promise((ok, error) => {
      console.log("download example project from repo");
      var download = require('download-git-repo');
      download('epaii/epii-vue-cli-project-example', __dirname + '/../project-example', function (err) {
        if(err)
         console.log('Error'+err);
         else ok();
      })
    })

  },
  build() {
    const config = require(__dirname + "/../webpack/webpack.production.js");
    var compiler = webpack(config, (err, res) => {
      if (err || res.hasErrors()) {
        console.log("构建过程出错！" + res);
      } else {
        console.log("构建成功！");
        let onbuid_file = process.cwd() + "/hooks/build.js";
        if (fs.existsSync(onbuid_file)) {
          let build_mod = require(onbuid_file);
          if (typeof build_mod === "function") {
            build_mod();
          }
        }
      }
    });
  },
  dev() {
    const config = require(__dirname + "/../webpack/webpack.location.js");
    var compiler = webpack(config);
    console.log(config.devServer)
    var server = new WebpackDevServer(compiler, config.devServer);
    var portfinder = require('portfinder');
    portfinder.basePort = 8800;
    portfinder.getPort(function (err, port) {
      server.listen(port);
    });
  },
  init: async function () {
    await this.dopull();
    let pfile = process.cwd() + "/package.json";
    if (fs.existsSync(pfile)) {
      console.log("检测到已经存在项目了");
      return;
    }
    console.log(
      "请选择项目模板\n" +
      "1、epii-vue 项目\n" +
      "2、epii-vue 带Eapp 项目\n" +
      "3、epii-vue 带一体机版本的Eapp 项目\n" +
      "4、uniapp 带Eapp 项目"
    );
    let leixing = await readline();

    if ((leixing == 1 || leixing == 2 || leixing == 3)) {

      copy(__dirname + "/../project-example/1", process.cwd());
      if (leixing == 2 || leixing == 3) {
        setTimeout(() => {
          let pdata = JSON.parse(fs.readFileSync(process.cwd() + "/package.json"));
          pdata.dependencies["eapp-h5-plus-vue"] = "latest";
          copy(__dirname + "/../project-example/2", process.cwd())
          if (leixing == 3) {
            pdata.dependencies["eapp-vue-yitiji"] = "latest";
            copy(__dirname + "/../project-example/3", process.cwd())
          }

          fs.writeFileSync(process.cwd() + "/package.json", JSON.stringify(pdata))
          console.log("Init Success，Get started with the following commands:\n run npm install")
        }, 100);

      }
    } else if (leixing == 4) {
      require("../tools/copydir.js")(__dirname + "/../project-example/4", process.cwd());
      console.log("Init Success，It is need run \n npm install \n open this dir from hbuilderx")
    }
  }
}





if (process.argv.length > 2) {

  if (runner.hasOwnProperty(process.argv[2])) {
    runner[process.argv[2]].apply(runner, process.argv.slice(3));
  } else {
    console.log(process.argv[2] + " error ")

  }
} else {
  runner.dev();
}

